config/routes.rb
Rails.application.routes.draw do

  resources :posts, only: %i(index show)

  #Casein routes
  namespace :casein do
    resources :menu_items do
      post :move, on: :member
    end
    resources :posts
    resources :pages do
      get :titles, on: :collection, format: :json
      post :image_upload, on: :collection, format: :json
    end
    resources :members do
      post :render_chart, on: :collection
    end
    resources :initiation_classes
  end

  get '*path', controller: :pages, action: :show
  root controller: :posts, action: :index
end

app/controllers/casein/initiation_classes_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class InitiationClassesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Initiation classes'
  		@initiation_classes = InitiationClass.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View initiation class'
      @initiation_class = InitiationClass.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new initiation class'
    	@initiation_class = InitiationClass.new
    end

    def create
      @initiation_class = InitiationClass.new initiation_class_params
    
      if @initiation_class.save
        flash[:notice] = 'Initiation class created'
        redirect_to casein_initiation_classes_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new initiation class'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update initiation class'
      
      @initiation_class = InitiationClass.find params[:id]
    
      if @initiation_class.update_attributes initiation_class_params
        flash[:notice] = 'Initiation class has been updated'
        redirect_to casein_initiation_classes_path
      else
        flash.now[:warning] = 'There were problems when trying to update this initiation class'
        render :action => :show
      end
    end
 
    def destroy
      @initiation_class = InitiationClass.find params[:id]

      @initiation_class.destroy
      flash[:notice] = 'Initiation class has been deleted'
      redirect_to casein_initiation_classes_path
    end
  
    private
      
      def initiation_class_params
        params.require(:initiation_class).permit(:name)
      end

  end
end

app/controllers/casein/members_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class MembersController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Members'
  		@members = Member.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View member'
      @member = Member.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new member'
    	@member = Member.new
    end

    def create
      @member = Member.new member_params
    
      if @member.save
        flash[:notice] = 'Member created'
        redirect_to casein_members_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new member'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update member'
      
      @member = Member.find params[:id]
    
      if @member.update_attributes member_params
        flash[:notice] = 'Member has been updated'
        redirect_to casein_members_path
      else
        flash.now[:warning] = 'There were problems when trying to update this member'
        render :action => :show
      end
    end
 
    def destroy
      @member = Member.find params[:id]

      @member.destroy
      flash[:notice] = 'Member has been deleted'
      redirect_to casein_members_path
    end
    
    def render_chart
      genealogy_file =
        RemoteFile.create_from_temp_file(role: :genealogy, suffix: '.pdf') do |temp_file|
          Member.output_graph(temp_file.path)
        end
      
      redirect_to genealogy_file.url
    end
  
    private
      
      def member_params
        base_params = params.require(:member).permit(:name, :status, :initiation_class_id, :big_brother_id)
        base_params[:member_attributes] = (params[:member_attributes]&.join(' ') || '')
        base_params
      end

  end
end

app/controllers/casein/menu_items_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class MenuItemsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Site Menu'
  		@menu_items = MenuItem.order(:position).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View menu item'
      @menu_item = MenuItem.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new menu item'
    	@menu_item = MenuItem.new
    end

    def create
      @menu_item = MenuItem.new menu_item_params
    
      if @menu_item.save
        flash[:notice] = 'Menu item created'
        redirect_to casein_menu_items_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new menu item'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update menu item'
      
      @menu_item = MenuItem.find params[:id]
    
      if @menu_item.update_attributes menu_item_params
        flash[:notice] = 'Menu item has been updated'
        redirect_to casein_menu_items_path
      else
        flash.now[:warning] = 'There were problems when trying to update this menu item'
        render :action => :show
      end
    end
    
    def move
      @menu_item = MenuItem.find params[:id]
      
      case params[:direction]
      when "up"
        @menu_item.move_higher
      when "down"
        @menu_item.move_lower
      when "top"
        @menu_item.move_to_top
      when "bottom"
        @menu_item.move_to_bottom
      end
      
      redirect_to casein_menu_items_path
    end
 
    def destroy
      @menu_item = MenuItem.find params[:id]

      @menu_item.destroy
      flash[:notice] = 'Menu item has been deleted'
      redirect_to casein_menu_items_path
    end
  
    private
      
      def menu_item_params
        params.require(:menu_item).permit(:position, :page_id)
      end

  end
end

app/controllers/casein/pages_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class PagesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Pages'
      @root_pages = Page.roots.order(:title)
    end
    
    def titles
      @pages = Page.all.paginate page: params[:page]
      
      respond_to do |format|
        format.json { render json:
          @pages.map { |page| {
            title: page.title,
            path: page.path
          }}
        }
      end
    end
  
    def show
      @casein_page_title = 'View page'
      @page = Page.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new page'
    	@page = Page.new
      @page.parent_id = params[:parent_id]
    end

    def create
      @page = Page.new page_params
    
      if @page.save
        flash[:notice] = 'Page created'
        redirect_to casein_pages_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new page'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update page'
      
      @page = Page.find params[:id]
    
      if @page.update_attributes page_params
        flash[:notice] = 'Page has been updated'
        redirect_to casein_pages_path
      else
        flash.now[:warning] = 'There were problems when trying to update this page'
        render :action => :show
      end
    end
 
    def destroy
      @page = Page.find params[:id]

      @page.destroy
      flash[:notice] = 'Page has been deleted'
      redirect_to casein_pages_path
    end
    
    def image_upload
      image_io = params[:image]
      image_file_extension = image_io.original_filename.split(/\./).last
      s3_file = RemoteFile.create_from io: image_io,
        role: :image,
        suffix: ".#{image_file_extension}"
      
      respond_to do |format|
        format.json { render json: {
          image_url: s3_file.url
        }}
      end
    end
  
    private
      
      def page_params
        base_params = params.require(:page).permit(:title, :slug, :published, :body, :sidebar, :parent_id)
      end

  end
end

app/controllers/casein/posts_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class PostsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Posts'
  		@posts = Post.order('created_at DESC').paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View post'
      @post = Post.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new post'
    	@post = Post.new
    end

    def create
      @post = Post.new post_params
    
      if @post.save
        flash[:notice] = 'Post created'
        redirect_to casein_posts_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new post'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update post'
      
      @post = Post.find params[:id]
    
      if @post.update_attributes post_params
        flash[:notice] = 'Post has been updated'
        redirect_to casein_posts_path
      else
        flash.now[:warning] = 'There were problems when trying to update this post'
        render :action => :show
      end
    end
 
    def destroy
      @post = Post.find params[:id]

      @post.destroy
      flash[:notice] = 'Post has been deleted'
      redirect_to casein_posts_path
    end
  
    private
      
      def post_params
        params.require(:post).permit(:title, :body, :published)
      end

  end
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'PsiU &Gamma;&Tau; Hall of Swords'.html_safe
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'psiu/admin.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://psiugt.org'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'network@gtpsiu.org'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      casein_posts_url
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end
    
  end
end

app/views/casein/pages/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->


<div class="row">
	<div class="col-lg-10">
		<%= casein_text_field f, f.object, :title %>
	</div>
	<div class="col-lg-2">
		<%= casein_check_box f, f.object, :published, casein_label: 'Published?' %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_collection_select f, f.object, :page, :parent_id, Page.all, :id, :title, include_blank: '(no parent page)' %>
	</div>
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :slug %>
	</div>
</div>

<div class="row">
	<div class="col-lg-8">
        <%= casein_custom_field f, f.object, :body, summernote_field(f, :body) %>
	</div>
	<div class="col-lg-4">
		<%= casein_custom_field f, f.object, :sidebar, summernote_field(f, :sidebar) %>
	</div>
</div>

app/views/casein/pages/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Title", :title %></th>
			<th>Path</th>
			<th>Status</th>
			<th>Parent Page</th>
			<th colspan="3">Actions</th>
		</tr>
	</thead>
	
    <tbody>
        <%= page_table_rows(pages) %>
    </tbody>
</table>

app/views/casein/pages/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>All Pages</h2>

<%= render :partial => 'casein/pages/table', :locals => { :pages => @root_pages } %>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new page".html_safe, new_casein_page_path %></li>
    <li><%= link_to "#{casein_show_icon "th-list"}Manage site menu".html_safe, casein_menu_items_path %></li>

<% end %>

app/views/casein/pages/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Add a new page</h2>

<%= form_for @page, :url => casein_pages_path do |f| %>
	
	<%= render :partial => 'casein/pages/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_pages_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new page", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_pages_path %></li>
<% end %>

app/views/casein/pages/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>View page</h2>

<% if @page.id == @home_page.id %>
<div class="alert alert-info">
    <h4>Home Page</h4>
    <p>As long as this page is published, its body will be shown above the news
        section on the home page and its sidebar content will be shown on every
        page.</p>
</div>
<% end %>
<% if @page.id == Page.not_found.id %>
<div class="alert alert-info">
    <h4>404 Page</h4>
    <p>As long as this page is published, its body will be shown whenever a
        viewer attempts to view a page or post that either doesn't exist or
        hasn't been published.</p>
</div>
<% end %>

<%= form_for @page, :url => casein_page_path(@page) do |f| %>

	<%= render :partial => 'casein/pages/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_pages_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_pages_path %></li>
<% end %>